package storage

func Seed(s *MemoryStore) {
	cars := []Car{
		{
			ID: "1", Brand: "Skoda", Model: "Kylaq", Variant: "Classic 1.0 TSI MT",
			PriceINR: 789000, BodyType: "suv", FuelType: "petrol",
			Transmission: "manual", SeatingCapacity: 5, MileageKMPL: 19.7,
			SafetyRating: 5.0, BootSpaceLitres: 446, CityScore: 8, HighwayScore: 7,
			FeatureTags: []string{"6-airbags", "esc", "touchscreen"},
		},
		{
			ID: "2", Brand: "Skoda", Model: "Kylaq", Variant: "Prestige 1.0 TSI AT",
			PriceINR: 1390000, BodyType: "suv", FuelType: "petrol",
			Transmission: "automatic", SeatingCapacity: 5, MileageKMPL: 19.0,
			SafetyRating: 5.0, BootSpaceLitres: 446, CityScore: 8, HighwayScore: 8,
			FeatureTags: []string{"sunroof", "6-airbags", "touchscreen", "ventilated-seats"},
		},
		{
			ID: "3", Brand: "Skoda", Model: "Kushaq", Variant: "Onyx 1.0 TSI MT",
			PriceINR: 1199000, BodyType: "suv", FuelType: "petrol",
			Transmission: "manual", SeatingCapacity: 5, MileageKMPL: 19.8,
			SafetyRating: 5.0, BootSpaceLitres: 385, CityScore: 8, HighwayScore: 8,
			FeatureTags: []string{"6-airbags", "esc", "touchscreen"},
		},
		{
			ID: "4", Brand: "Skoda", Model: "Kushaq", Variant: "Style 1.5 TSI DSG",
			PriceINR: 1899000, BodyType: "suv", FuelType: "petrol",
			Transmission: "automatic", SeatingCapacity: 5, MileageKMPL: 18.6,
			SafetyRating: 5.0, BootSpaceLitres: 385, CityScore: 7, HighwayScore: 9,
			FeatureTags: []string{"sunroof", "6-airbags", "wireless-charging", "ventilated-seats"},
		},
		{
			ID: "5", Brand: "Skoda", Model: "Slavia", Variant: "Classic 1.0 TSI MT",
			PriceINR: 1089000, BodyType: "sedan", FuelType: "petrol",
			Transmission: "manual", SeatingCapacity: 5, MileageKMPL: 20.3,
			SafetyRating: 5.0, BootSpaceLitres: 521, CityScore: 8, HighwayScore: 9,
			FeatureTags: []string{"6-airbags", "esc", "touchscreen"},
		},
		{
			ID: "6", Brand: "Skoda", Model: "Slavia", Variant: "Style 1.5 TSI DSG",
			PriceINR: 1879000, BodyType: "sedan", FuelType: "petrol",
			Transmission: "automatic", SeatingCapacity: 5, MileageKMPL: 19.4,
			SafetyRating: 5.0, BootSpaceLitres: 521, CityScore: 7, HighwayScore: 9,
			FeatureTags: []string{"sunroof", "6-airbags", "ventilated-seats", "digital-cluster"},
		},
		{
			ID: "7", Brand: "Skoda", Model: "Kodiaq", Variant: "Sportline 2.0 TSI DSG",
			PriceINR: 3899000, BodyType: "suv", FuelType: "petrol",
			Transmission: "automatic", SeatingCapacity: 7, MileageKMPL: 13.3,
			SafetyRating: 5.0, BootSpaceLitres: 270, CityScore: 6, HighwayScore: 9,
			FeatureTags: []string{"adas", "9-airbags", "panoramic-roof", "360-camera"},
		},
		{
			ID: "8", Brand: "Skoda", Model: "Superb", Variant: "L&K 2.0 TSI DSG",
			PriceINR: 5400000, BodyType: "sedan", FuelType: "petrol",
			Transmission: "automatic", SeatingCapacity: 5, MileageKMPL: 15.1,
			SafetyRating: 5.0, BootSpaceLitres: 625, CityScore: 6, HighwayScore: 9,
			FeatureTags: []string{"adas", "9-airbags", "ventilated-seats", "premium-audio"},
		},
		{
			ID: "9", Brand: "Tata", Model: "Tiago", Variant: "XZ+",
			PriceINR: 780000, BodyType: "hatchback", FuelType: "petrol",
			Transmission: "manual", SeatingCapacity: 5, MileageKMPL: 20.1,
			SafetyRating: 4.0, BootSpaceLitres: 242, CityScore: 8, HighwayScore: 7,
			FeatureTags: []string{"touchscreen", "auto-ac", "rear-camera"},
		},
		{
			ID: "10", Brand: "Tata", Model: "Tiago EV", Variant: "XZ+ LR",
			PriceINR: 1199000, BodyType: "hatchback", FuelType: "ev",
			Transmission: "automatic", SeatingCapacity: 5, MileageKMPL: 0,
			SafetyRating: 4.0, BootSpaceLitres: 240, CityScore: 10, HighwayScore: 7,
			FeatureTags: []string{"fast-charge", "regen-modes", "touchscreen"},
		},
		{
			ID: "11", Brand: "Tata", Model: "Tigor", Variant: "XZ+",
			PriceINR: 900000, BodyType: "sedan", FuelType: "petrol",
			Transmission: "manual", SeatingCapacity: 5, MileageKMPL: 19.3,
			SafetyRating: 4.0, BootSpaceLitres: 419, CityScore: 8, HighwayScore: 7,
			FeatureTags: []string{"touchscreen", "auto-ac", "rear-camera"},
		},
		{
			ID: "12", Brand: "Tata", Model: "Tigor EV", Variant: "XZ+ LR",
			PriceINR: 1299000, BodyType: "sedan", FuelType: "ev",
			Transmission: "automatic", SeatingCapacity: 5, MileageKMPL: 0,
			SafetyRating: 4.0, BootSpaceLitres: 316, CityScore: 10, HighwayScore: 7,
			FeatureTags: []string{"fast-charge", "touchscreen", "connected-car"},
		},
		{
			ID: "13", Brand: "Tata", Model: "Altroz", Variant: "XZ+",
			PriceINR: 980000, BodyType: "hatchback", FuelType: "petrol",
			Transmission: "manual", SeatingCapacity: 5, MileageKMPL: 19.3,
			SafetyRating: 5.0, BootSpaceLitres: 345, CityScore: 8, HighwayScore: 8,
			FeatureTags: []string{"6-airbags", "touchscreen", "auto-ac"},
		},
		{
			ID: "14", Brand: "Tata", Model: "Altroz Racer", Variant: "R3",
			PriceINR: 1190000, BodyType: "hatchback", FuelType: "petrol",
			Transmission: "manual", SeatingCapacity: 5, MileageKMPL: 18.0,
			SafetyRating: 5.0, BootSpaceLitres: 345, CityScore: 7, HighwayScore: 8,
			FeatureTags: []string{"sunroof", "6-airbags", "sport-mode", "touchscreen"},
		},
		{
			ID: "15", Brand: "Tata", Model: "Punch", Variant: "Creative+",
			PriceINR: 1020000, BodyType: "suv", FuelType: "petrol",
			Transmission: "manual", SeatingCapacity: 5, MileageKMPL: 20.1,
			SafetyRating: 5.0, BootSpaceLitres: 366, CityScore: 8, HighwayScore: 7,
			FeatureTags: []string{"touchscreen", "cruise-control", "6-airbags"},
		},
		{
			ID: "16", Brand: "Tata", Model: "Punch EV", Variant: "Empowered+ LR",
			PriceINR: 1399000, BodyType: "suv", FuelType: "ev",
			Transmission: "automatic", SeatingCapacity: 5, MileageKMPL: 0,
			SafetyRating: 5.0, BootSpaceLitres: 366, CityScore: 10, HighwayScore: 8,
			FeatureTags: []string{"fast-charge", "360-camera", "connected-car"},
		},
		{
			ID: "17", Brand: "Tata", Model: "Nexon", Variant: "Fearless+",
			PriceINR: 1450000, BodyType: "suv", FuelType: "petrol",
			Transmission: "automatic", SeatingCapacity: 5, MileageKMPL: 17.4,
			SafetyRating: 5.0, BootSpaceLitres: 382, CityScore: 8, HighwayScore: 8,
			FeatureTags: []string{"6-airbags", "sunroof", "360-camera", "touchscreen"},
		},
		{
			ID: "18", Brand: "Tata", Model: "Nexon EV", Variant: "Empowered+ LR",
			PriceINR: 1749000, BodyType: "suv", FuelType: "ev",
			Transmission: "automatic", SeatingCapacity: 5, MileageKMPL: 0,
			SafetyRating: 5.0, BootSpaceLitres: 350, CityScore: 10, HighwayScore: 8,
			FeatureTags: []string{"fast-charge", "adas", "360-camera"},
		},
		{
			ID: "19", Brand: "Tata", Model: "Curvv", Variant: "Accomplished+",
			PriceINR: 1749000, BodyType: "suv", FuelType: "petrol",
			Transmission: "automatic", SeatingCapacity: 5, MileageKMPL: 16.5,
			SafetyRating: 5.0, BootSpaceLitres: 500, CityScore: 7, HighwayScore: 8,
			FeatureTags: []string{"panoramic-roof", "adas", "6-airbags", "360-camera"},
		},
		{
			ID: "20", Brand: "Tata", Model: "Curvv EV", Variant: "Empowered+ A",
			PriceINR: 2199000, BodyType: "suv", FuelType: "ev",
			Transmission: "automatic", SeatingCapacity: 5, MileageKMPL: 0,
			SafetyRating: 5.0, BootSpaceLitres: 500, CityScore: 10, HighwayScore: 8,
			FeatureTags: []string{"fast-charge", "adas", "panoramic-roof", "ventilated-seats"},
		},
		{
			ID: "21", Brand: "Tata", Model: "Harrier", Variant: "Fearless+ AT",
			PriceINR: 2660000, BodyType: "suv", FuelType: "diesel",
			Transmission: "automatic", SeatingCapacity: 5, MileageKMPL: 14.6,
			SafetyRating: 5.0, BootSpaceLitres: 445, CityScore: 6, HighwayScore: 9,
			FeatureTags: []string{"adas", "panoramic-roof", "360-camera", "7-airbags"},
		},
		{
			ID: "22", Brand: "Tata", Model: "Safari", Variant: "Accomplished+ AT",
			PriceINR: 2920000, BodyType: "suv", FuelType: "diesel",
			Transmission: "automatic", SeatingCapacity: 7, MileageKMPL: 14.1,
			SafetyRating: 5.0, BootSpaceLitres: 420, CityScore: 6, HighwayScore: 9,
			FeatureTags: []string{"adas", "panoramic-roof", "360-camera", "7-airbags"},
		},
		{
			ID: "23", Brand: "Maruti", Model: "Alto K10", Variant: "VXi",
			PriceINR: 540000, BodyType: "hatchback", FuelType: "petrol",
			Transmission: "manual", SeatingCapacity: 5, MileageKMPL: 24.4,
			SafetyRating: 2.0, BootSpaceLitres: 214, CityScore: 9, HighwayScore: 6,
			FeatureTags: []string{"touchscreen", "power-windows"},
		},
		{
			ID: "24", Brand: "Maruti", Model: "Alto K10", Variant: "VXi CNG",
			PriceINR: 640000, BodyType: "hatchback", FuelType: "cng",
			Transmission: "manual", SeatingCapacity: 5, MileageKMPL: 33.9,
			SafetyRating: 2.0, BootSpaceLitres: 214, CityScore: 9, HighwayScore: 6,
			FeatureTags: []string{"cng-kit", "touchscreen"},
		},
		{
			ID: "25", Brand: "Maruti", Model: "S-Presso", Variant: "VXi+",
			PriceINR: 620000, BodyType: "hatchback", FuelType: "petrol",
			Transmission: "manual", SeatingCapacity: 5, MileageKMPL: 24.1,
			SafetyRating: 2.0, BootSpaceLitres: 240, CityScore: 8, HighwayScore: 6,
			FeatureTags: []string{"touchscreen", "hill-hold"},
		},
		{
			ID: "26", Brand: "Maruti", Model: "WagonR", Variant: "ZXi 1.2",
			PriceINR: 720000, BodyType: "hatchback", FuelType: "petrol",
			Transmission: "manual", SeatingCapacity: 5, MileageKMPL: 23.6,
			SafetyRating: 2.0, BootSpaceLitres: 341, CityScore: 9, HighwayScore: 6,
			FeatureTags: []string{"touchscreen", "rear-camera"},
		},
		{
			ID: "27", Brand: "Maruti", Model: "WagonR", Variant: "LXi CNG",
			PriceINR: 760000, BodyType: "hatchback", FuelType: "cng",
			Transmission: "manual", SeatingCapacity: 5, MileageKMPL: 34.0,
			SafetyRating: 2.0, BootSpaceLitres: 341, CityScore: 9, HighwayScore: 6,
			FeatureTags: []string{"cng-kit", "dual-airbags"},
		},
		{
			ID: "28", Brand: "Maruti", Model: "Celerio", Variant: "ZXi",
			PriceINR: 700000, BodyType: "hatchback", FuelType: "petrol",
			Transmission: "manual", SeatingCapacity: 5, MileageKMPL: 25.2,
			SafetyRating: 3.0, BootSpaceLitres: 313, CityScore: 9, HighwayScore: 7,
			FeatureTags: []string{"touchscreen", "push-start"},
		},
		{
			ID: "29", Brand: "Maruti", Model: "Swift", Variant: "ZXi AMT",
			PriceINR: 910000, BodyType: "hatchback", FuelType: "petrol",
			Transmission: "automatic", SeatingCapacity: 5, MileageKMPL: 24.8,
			SafetyRating: 3.0, BootSpaceLitres: 265, CityScore: 9, HighwayScore: 7,
			FeatureTags: []string{"touchscreen", "rear-camera", "cruise-control"},
		},
		{
			ID: "30", Brand: "Maruti", Model: "Baleno", Variant: "Alpha AMT",
			PriceINR: 1020000, BodyType: "hatchback", FuelType: "petrol",
			Transmission: "automatic", SeatingCapacity: 5, MileageKMPL: 22.9,
			SafetyRating: 3.0, BootSpaceLitres: 318, CityScore: 8, HighwayScore: 7,
			FeatureTags: []string{"hud", "360-camera", "touchscreen"},
		},
		{
			ID: "31", Brand: "Maruti", Model: "Fronx", Variant: "Alpha 1.0 AT",
			PriceINR: 1310000, BodyType: "suv", FuelType: "petrol",
			Transmission: "automatic", SeatingCapacity: 5, MileageKMPL: 20.0,
			SafetyRating: 3.0, BootSpaceLitres: 308, CityScore: 8, HighwayScore: 8,
			FeatureTags: []string{"hud", "360-camera", "turbo"},
		},
		{
			ID: "32", Brand: "Maruti", Model: "Fronx", Variant: "Delta CNG",
			PriceINR: 980000, BodyType: "suv", FuelType: "cng",
			Transmission: "manual", SeatingCapacity: 5, MileageKMPL: 28.5,
			SafetyRating: 3.0, BootSpaceLitres: 308, CityScore: 8, HighwayScore: 7,
			FeatureTags: []string{"cng-kit", "touchscreen"},
		},
		{
			ID: "33", Brand: "Maruti", Model: "Brezza", Variant: "ZXi AT",
			PriceINR: 1420000, BodyType: "suv", FuelType: "petrol",
			Transmission: "automatic", SeatingCapacity: 5, MileageKMPL: 19.8,
			SafetyRating: 4.0, BootSpaceLitres: 328, CityScore: 8, HighwayScore: 7,
			FeatureTags: []string{"sunroof", "360-camera", "touchscreen"},
		},
		{
			ID: "34", Brand: "Maruti", Model: "Grand Vitara", Variant: "Zeta AT",
			PriceINR: 1650000, BodyType: "suv", FuelType: "petrol",
			Transmission: "automatic", SeatingCapacity: 5, MileageKMPL: 20.6,
			SafetyRating: 4.0, BootSpaceLitres: 373, CityScore: 8, HighwayScore: 8,
			FeatureTags: []string{"panoramic-roof", "360-camera", "touchscreen"},
		},
		{
			ID: "35", Brand: "Maruti", Model: "Grand Vitara", Variant: "Strong Hybrid Alpha",
			PriceINR: 1990000, BodyType: "suv", FuelType: "hybrid",
			Transmission: "automatic", SeatingCapacity: 5, MileageKMPL: 27.9,
			SafetyRating: 4.0, BootSpaceLitres: 265, CityScore: 9, HighwayScore: 8,
			FeatureTags: []string{"hybrid", "360-camera", "hud"},
		},
		{
			ID: "36", Brand: "Maruti", Model: "Jimny", Variant: "Alpha AT",
			PriceINR: 1305000, BodyType: "suv", FuelType: "petrol",
			Transmission: "automatic", SeatingCapacity: 4, MileageKMPL: 16.9,
			SafetyRating: 3.0, BootSpaceLitres: 208, CityScore: 6, HighwayScore: 7,
			FeatureTags: []string{"4x4", "hill-descent", "touchscreen"},
		},
		{
			ID: "37", Brand: "Maruti", Model: "Dzire", Variant: "ZXi AMT",
			PriceINR: 960000, BodyType: "sedan", FuelType: "petrol",
			Transmission: "automatic", SeatingCapacity: 5, MileageKMPL: 24.8,
			SafetyRating: 3.0, BootSpaceLitres: 378, CityScore: 9, HighwayScore: 7,
			FeatureTags: []string{"touchscreen", "rear-camera", "cruise-control"},
		},
		{
			ID: "38", Brand: "Maruti", Model: "Ciaz", Variant: "Alpha AT",
			PriceINR: 1260000, BodyType: "sedan", FuelType: "petrol",
			Transmission: "automatic", SeatingCapacity: 5, MileageKMPL: 20.0,
			SafetyRating: 3.0, BootSpaceLitres: 510, CityScore: 8, HighwayScore: 8,
			FeatureTags: []string{"cruise-control", "touchscreen", "led-headlamps"},
		},
		{
			ID: "39", Brand: "Maruti", Model: "Ertiga", Variant: "ZXi AT",
			PriceINR: 1320000, BodyType: "mpv", FuelType: "petrol",
			Transmission: "automatic", SeatingCapacity: 7, MileageKMPL: 20.3,
			SafetyRating: 3.0, BootSpaceLitres: 209, CityScore: 8, HighwayScore: 8,
			FeatureTags: []string{"7-seater", "touchscreen", "rear-ac"},
		},
		{
			ID: "40", Brand: "Maruti", Model: "Ertiga", Variant: "VXi CNG",
			PriceINR: 1170000, BodyType: "mpv", FuelType: "cng",
			Transmission: "manual", SeatingCapacity: 7, MileageKMPL: 26.1,
			SafetyRating: 3.0, BootSpaceLitres: 209, CityScore: 8, HighwayScore: 7,
			FeatureTags: []string{"7-seater", "cng-kit", "rear-ac"},
		},
		{
			ID: "41", Brand: "Maruti", Model: "XL6", Variant: "Alpha+ AT",
			PriceINR: 1359000, BodyType: "mpv", FuelType: "petrol",
			Transmission: "automatic", SeatingCapacity: 6, MileageKMPL: 20.3,
			SafetyRating: 3.0, BootSpaceLitres: 209, CityScore: 8, HighwayScore: 8,
			FeatureTags: []string{"captain-seats", "360-camera", "touchscreen"},
		},
		{
			ID: "42", Brand: "Maruti", Model: "Invicto", Variant: "Alpha+",
			PriceINR: 2842000, BodyType: "mpv", FuelType: "hybrid",
			Transmission: "automatic", SeatingCapacity: 7, MileageKMPL: 23.2,
			SafetyRating: 5.0, BootSpaceLitres: 239, CityScore: 8, HighwayScore: 9,
			FeatureTags: []string{"adas", "panoramic-roof", "360-camera", "captain-seats"},
		},
		{
			ID: "43", Brand: "Maruti", Model: "Eeco", Variant: "5-Seater AC",
			PriceINR: 610000, BodyType: "mpv", FuelType: "petrol",
			Transmission: "manual", SeatingCapacity: 5, MileageKMPL: 19.7,
			SafetyRating: 1.0, BootSpaceLitres: 540, CityScore: 7, HighwayScore: 6,
			FeatureTags: []string{"dual-airbags", "ac"},
		},
	}

	for _, c := range cars {
		s.AddCar(c)
	}
}
